spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mapu?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  web:
    resources:
      static-locations: classpath:/static/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hniu.mapu.pojo.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

server:
  port: 8081
# 文件上传配置
file.upload-dir: uploads
# 静态资源访问
spring.web.resources.static-locations: classpath:/static/,file:./uploads/
